name: CI

on: [push]
jobs:
  job:
    name: cmake-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install C++20 compiler
        run: |
         sudo apt update
         sudo apt install gcc-10 g++-10
      - name: Generate Makefile
        run: cmake .
        env:
            CXX:  g++-10
      - name: Build
        run: make
      - name: Test
        run: make test
        
