name: CI

on: [push]
jobs:
  job:
    name: cmake-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Makefile
        run: cmake .
      - name: Build
        run: make
      - name: Test
        run: make test
        
